version: '3'

networks:
  net:
    driver: bridge
services:
  chromadb:
    image: chromadb/chroma:0.5.13
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8002:8002
    networks:
      - net